baseURL = "https://yinli.work/"
languageCode = "zh_CN"
title = "引力社"
theme = "hugo-cards"
paginate = 6

[params]
  builtBy = "bool"
  defaultImage = "default.jpeg"

  facebook = ""
  quora = ""
  twitter = ""
  github = "http://github.com/yinliwork"
  email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  disqus = ""
  
  custom_css = ["css/custom.css"]

  [params.analytics]
    type="UA"
    trackingID = ""

  [params.copyright]
     name = "引力社"
     link = "https://yinli.work/"

